language: go
sudo: 'required'
go:
  - master

script:
  - 'make test'
  - 'make image'


services:
  - 'docker'

after_success:
  - 'make push-image'


env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "e/ZrRzHuPsmmLU+XRY797Gc9lr+EFyWfcPaySO0CAtsbybBJyEwmQw+oJ06JiBUXPGMQksClX+iDYvnObuvfTH06RvyeHFuUFFzzGqPgV0V6Chp/AcjL+pI+gu6VBmhQoAHEwnNUgk1W0Nka+SyDMfJA3vLDA0DXEnh/2Z/uA8BxRVxdJ+yn7hOzl1ljcamXEjSU76BURlYzn3i9uAyv6C6/r5zAVF9swoy5WA0NYZm1TeoBdXmJ7y3IssHXwkwC3+17jOeaHD4OlbhgDIAgJV5YpqGSG4/rDxjOeW1BPv0dD0fXhOMBgBxNMOtxEECTCxr984jyIhsNd9ked2HIVoW2VfBPLOOcXS6ZVV1qf+5Tm9Ys3EKClI7K3Af9BXYpM6f2rt3L4TxkdA/OMWqmwmjxyDNe9KkMpjxGfSd64SZI1AmPG/Bm/+Lbm7sR5HF98cVaRtUYT2eyxF1Zuau9XiPZIpZZmTuIGQ9NHM7ztZ0fCiKLxi/lPy/+se3XFgVbDuyELgOV/8SNBqFCj4gkOyH+1OJa3fd4m0NT+u4u5qPCdLuWw5zNvnqB9bISHo3VeJRpq6YRnYp/DXE20Pkwg5GfHOZs4HkZ/3gkxZr2eIAkgFb2F8DzpPQbT/Bkx7y8IprYnRtjFd5le17eNPD3AeOX+ZchtikzyqTWc2BHIX0="
    - secure: "WavFRqWE4ft53CK14MHoXeiW2ycgz0uk2TVvHgaY8iGFRkXj4V7igbNs6ueRSmJMm8Zn2UPxrmGioAOLcFDmvONOm0vIA/zZ6qiJJNBmFd1dkLcyozrmVDYyEUKutKKwGRuYW3H0rJVZJZxDL6VWbbzSrS7LYf44HJUt0z88BOx5jzSkHUoj8mKyqJPWJpN6/jbzWb4WZdWUvaf6a9yO2MYhkZntO4BX7TGUszdWGBQnYNYeiHkPUdsn6o979swoXdhCKrsVyrBVJoDSvaYr876HD8Z7AxiOURg/2WNL22fmC1DQOYx836kZfUala02AF3nLz1tnGwUnf/zJhGk8jNtuQrDzBRR5qtOfIAUbWn5q0eqg1NKDprzWzNWb/pKrbm22ZDRji5EaIJsUHBdPUPN2+Hs4B8HkeC+IIIPPo78/GY5tDCRD8kvfM6ScUg6ll7FsoLJktLsmgl/LrMxP3c5lmVGz5Oq5asLqWxcp4nWzy6dj3RGvnnD6Sit/tdWLOFRDHbcudbVghUalCM0ZMVQ2rfAFFfYRIIniZ0gZtxKeKdjokAr9+c5yztzKFQEi81ZWJw4WjwxVY5qT5SBT7yQG8wdmqhq4eYcgbmv70k2tc7FO2jPdnfHDFN8DBz/qHkDPnQULhAr8g3QILdqP9H3z5FRH3R1SY2GlDagqBUU="
