language: go
sudo: 'required'
go:
  - master

script:
  - 'make test'
  - 'make image'


services:
  - 'docker'

after_success:
  — 'export  TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`'
  - 'make push-image'


env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}