language: go
sudo: 'required'
go:
  - "1.11"
  - master

script:
  - 'make test'
  - 'make image'


services:
  - 'docker'

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push vvizard/trlogic


env:
  global:
    - secure: "Ly7hscTB81Dzwrwko5F8xt6syEh7qO7l0mYNAt8LX3xk8MwoVgoaCLThwx2M+q0O3GxJWxGs4IVEe/+8VGG+bkxYG5fgUMlfCom+hZ2hUEHaeZOEHsTLlJI41Evjv+9fQteoHTz8Fy7aYv5opJbcJ0DgPp/8/cy+Hgm7ys0N9RL6/lYSOQZgybtXx+u1aZJennXYYkc/eiRccpbNAP95wNDZTfQf5ijHo6mPwORkaelZrszJICbWF4zakVNM+7CZ6nE+p+nJaweBrbE8QQ3fmRpSRFZn//NTo5cvg1X0lOjHnz/Nqxjf+GeKej4TZthcaLDi/Ah/Wb98H5b1fr/emCBrCmCW5xdYvENBca7uTBPBTb2rZ7p2ZZE/EJ560gO2gM63IGuzcvAye2nkqtyp7uivbIKFRzq7X6F+W4JlzAXQ9HMfCHXSWl+VcNjOaVd7YRBrmQLCLHt0L5tKLvSYRAizvxi2avQbIQYUHN0ZnrEZ4HV15sGzYOdlLTelwUfT6fxjf94S5buU1owuf/dRck0hyP87DOEOXJa0bfHF9dPez7RAr9ErZn4QSqaS6nXhPmK1aBeymJJOV01VAlNR0UPSjwr/GjfLmS4OqRqc8d3VR4XO1t6aJCdTmhmJBjzw+tgsbp5jvTGhhZt3tGMVwii0cfxl6XANvRYnlw60XIk="
    - secure: "e/ZrRzHuPsmmLU+XRY797Gc9lr+EFyWfcPaySO0CAtsbybBJyEwmQw+oJ06JiBUXPGMQksClX+iDYvnObuvfTH06RvyeHFuUFFzzGqPgV0V6Chp/AcjL+pI+gu6VBmhQoAHEwnNUgk1W0Nka+SyDMfJA3vLDA0DXEnh/2Z/uA8BxRVxdJ+yn7hOzl1ljcamXEjSU76BURlYzn3i9uAyv6C6/r5zAVF9swoy5WA0NYZm1TeoBdXmJ7y3IssHXwkwC3+17jOeaHD4OlbhgDIAgJV5YpqGSG4/rDxjOeW1BPv0dD0fXhOMBgBxNMOtxEECTCxr984jyIhsNd9ked2HIVoW2VfBPLOOcXS6ZVV1qf+5Tm9Ys3EKClI7K3Af9BXYpM6f2rt3L4TxkdA/OMWqmwmjxyDNe9KkMpjxGfSd64SZI1AmPG/Bm/+Lbm7sR5HF98cVaRtUYT2eyxF1Zuau9XiPZIpZZmTuIGQ9NHM7ztZ0fCiKLxi/lPy/+se3XFgVbDuyELgOV/8SNBqFCj4gkOyH+1OJa3fd4m0NT+u4u5qPCdLuWw5zNvnqB9bISHo3VeJRpq6YRnYp/DXE20Pkwg5GfHOZs4HkZ/3gkxZr2eIAkgFb2F8DzpPQbT/Bkx7y8IprYnRtjFd5le17eNPD3AeOX+ZchtikzyqTWc2BHIX0="
    - secure: "WavFRqWE4ft53CK14MHoXeiW2ycgz0uk2TVvHgaY8iGFRkXj4V7igbNs6ueRSmJMm8Zn2UPxrmGioAOLcFDmvONOm0vIA/zZ6qiJJNBmFd1dkLcyozrmVDYyEUKutKKwGRuYW3H0rJVZJZxDL6VWbbzSrS7LYf44HJUt0z88BOx5jzSkHUoj8mKyqJPWJpN6/jbzWb4WZdWUvaf6a9yO2MYhkZntO4BX7TGUszdWGBQnYNYeiHkPUdsn6o979swoXdhCKrsVyrBVJoDSvaYr876HD8Z7AxiOURg/2WNL22fmC1DQOYx836kZfUala02AF3nLz1tnGwUnf/zJhGk8jNtuQrDzBRR5qtOfIAUbWn5q0eqg1NKDprzWzNWb/pKrbm22ZDRji5EaIJsUHBdPUPN2+Hs4B8HkeC+IIIPPo78/GY5tDCRD8kvfM6ScUg6ll7FsoLJktLsmgl/LrMxP3c5lmVGz5Oq5asLqWxcp4nWzy6dj3RGvnnD6Sit/tdWLOFRDHbcudbVghUalCM0ZMVQ2rfAFFfYRIIniZ0gZtxKeKdjokAr9+c5yztzKFQEi81ZWJw4WjwxVY5qT5SBT7yQG8wdmqhq4eYcgbmv70k2tc7FO2jPdnfHDFN8DBz/qHkDPnQULhAr8g3QILdqP9H3z5FRH3R1SY2GlDagqBUU="
